#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker2012"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "76867b91236b4069b4b7666736c0ebc4" }
]

[assets]
directory = "./public"
